import Theme from "./component/theme"
import "./globals.css";
import {WeatherProvider} from "./context/weather"

export const metadata = {
  title: "NayaMausam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" className=" ">
      <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0EPSJSHV79"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0EPSJSHV79');
</script>
      <WeatherProvider>
              <body
        className={` duration-200 h-[120vh] dark:bg-black bg-white  `}
      >
       <h1 className=" text-center   dark:text-white text-blue-400 font-bold text-4xl pt-20 sm:pt-10 ">
            Weather Forecast App
          </h1><Theme />   
          {children}
      </body>
      </WeatherProvider>
    </html>
  );
}
